apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ds
  name: ds
  namespace: bosun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: ds
  name: ds:view
  namespace: bosun
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: ds
subjects:
  - kind: ServiceAccount
    name: ds
    namespace: bosun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bosun
  name: ds
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
